CREATE TABLE party (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    driver_member_id BIGINT NOT NULL,
    title VARCHAR(200),
    description TEXT,
    origin_name VARCHAR(100) NOT NULL,
    origin_lat DOUBLE PRECISION NOT NULL,
    origin_lng DOUBLE PRECISION NOT NULL,
    destination_name VARCHAR(100) NOT NULL,
    dest_lat DOUBLE PRECISION NOT NULL,
    dest_lng DOUBLE PRECISION NOT NULL,
    departure_time TIMESTAMP NOT NULL,
    arrival_time TIMESTAMP NOT NULL,
    max_passengers INTEGER NOT NULL,
    current_passengers INTEGER NOT NULL DEFAULT 0,
    status VARCHAR(20) NOT NULL DEFAULT 'RECRUITING',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_party_status
        CHECK (status IN ('RECRUITING', 'CLOSED', 'IN_PROGRESS', 'COMPLETED')),
    CONSTRAINT chk_party_passengers
        CHECK (max_passengers > 0 AND current_passengers >= 0 AND current_passengers <= max_passengers),
    CONSTRAINT chk_party_times
        CHECK (arrival_time > departure_time)
);

CREATE TABLE party_waypoint (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    party_id BIGINT NOT NULL,
    order_index INTEGER NOT NULL,
    name VARCHAR(100) NOT NULL,
    latitude DOUBLE PRECISION NOT NULL,
    longitude DOUBLE PRECISION NOT NULL,
    estimated_arrival TIMESTAMP,
    CONSTRAINT fk_party_waypoint_party
        FOREIGN KEY (party_id) REFERENCES party (id) ON DELETE CASCADE,
    CONSTRAINT uk_party_waypoint_party_order
        UNIQUE (party_id, order_index),
    CONSTRAINT chk_party_waypoint_order
        CHECK (order_index BETWEEN 1 AND 3),
    CONSTRAINT chk_party_waypoint_lat_lng
        CHECK (latitude BETWEEN -90 AND 90 AND longitude BETWEEN -180 AND 180)
);

CREATE TABLE party_participant (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    party_id BIGINT NOT NULL,
    member_id BIGINT NOT NULL,
    pickup_name VARCHAR(100),
    pickup_lat DOUBLE PRECISION,
    pickup_lng DOUBLE PRECISION,
    dropoff_name VARCHAR(100),
    dropoff_lat DOUBLE PRECISION,
    dropoff_lng DOUBLE PRECISION,
    point_cost INTEGER,
    payment_debited BOOLEAN NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    cancel_reason VARCHAR(200),
    cancelled_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_party_participant_party
        FOREIGN KEY (party_id) REFERENCES party (id) ON DELETE CASCADE,
    CONSTRAINT uk_party_participant_party_member
        UNIQUE (party_id, member_id),
    CONSTRAINT chk_party_participant_status
        CHECK (status IN ('PENDING', 'ACCEPTED', 'REJECTED', 'CANCELLED')),
    CONSTRAINT chk_party_participant_pickup_lat_lng
        CHECK (
            (pickup_lat IS NULL OR pickup_lat BETWEEN -90 AND 90)
            AND (pickup_lng IS NULL OR pickup_lng BETWEEN -180 AND 180)
        ),
    CONSTRAINT chk_party_participant_dropoff_lat_lng
        CHECK (
            (dropoff_lat IS NULL OR dropoff_lat BETWEEN -90 AND 90)
            AND (dropoff_lng IS NULL OR dropoff_lng BETWEEN -180 AND 180)
        ),
    CONSTRAINT chk_party_participant_point_cost
        CHECK (point_cost IS NULL OR point_cost >= 0)
);

CREATE TABLE point_refund_outbox (
    point_refund_outbox_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id VARCHAR(100) NOT NULL,
    member_id BIGINT NOT NULL,
    amount INTEGER NOT NULL,
    party_id BIGINT NOT NULL,
    participant_id BIGINT NOT NULL,
    status VARCHAR(30) NOT NULL,
    attempt_count INTEGER NOT NULL DEFAULT 0,
    last_error VARCHAR(500),
    next_retry_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    processed_at TIMESTAMP,
    CONSTRAINT uk_point_refund_outbox_request_id
        UNIQUE (request_id),
    CONSTRAINT chk_point_refund_outbox_status
        CHECK (status IN ('PENDING', 'PROCESSING', 'SUCCEEDED', 'FAILED_RETRYABLE', 'FAILED_MANUAL_REVIEW')),
    CONSTRAINT chk_point_refund_outbox_amount
        CHECK (amount > 0),
    CONSTRAINT chk_point_refund_outbox_attempt_count
        CHECK (attempt_count >= 0)
);

CREATE TABLE point_credit_outbox (
    point_credit_outbox_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id VARCHAR(100) NOT NULL,
    member_id BIGINT NOT NULL,
    amount INTEGER NOT NULL,
    party_id BIGINT NOT NULL,
    status VARCHAR(30) NOT NULL,
    attempt_count INTEGER NOT NULL DEFAULT 0,
    last_error VARCHAR(500),
    next_retry_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    processed_at TIMESTAMP,
    CONSTRAINT uk_point_credit_outbox_request_id
        UNIQUE (request_id),
    CONSTRAINT chk_point_credit_outbox_status
        CHECK (status IN ('PENDING', 'PROCESSING', 'SUCCEEDED', 'FAILED_RETRYABLE', 'FAILED_MANUAL_REVIEW')),
    CONSTRAINT chk_point_credit_outbox_amount
        CHECK (amount > 0),
    CONSTRAINT chk_point_credit_outbox_attempt_count
        CHECK (attempt_count >= 0)
);

CREATE INDEX idx_party_driver_member_departure
    ON party (driver_member_id, departure_time);

CREATE INDEX idx_party_search
    ON party (status, departure_time, arrival_time);

CREATE INDEX idx_party_participant_member_status
    ON party_participant (member_id, status);

CREATE INDEX idx_party_participant_party_status
    ON party_participant (party_id, status, id);

CREATE INDEX idx_party_waypoint_party_order
    ON party_waypoint (party_id, order_index);

CREATE INDEX idx_point_refund_outbox_ready
    ON point_refund_outbox (status, next_retry_at, created_at);

CREATE INDEX idx_point_refund_outbox_stale
    ON point_refund_outbox (status, updated_at);

CREATE INDEX idx_point_credit_outbox_ready
    ON point_credit_outbox (status, next_retry_at, created_at);

CREATE INDEX idx_point_credit_outbox_stale
    ON point_credit_outbox (status, updated_at);
